### PR TITLE
Adding languages support

### PR DESCRIPTION
**Pull request by Herz3h**

### CODE REVIEW

**Comment by lukasoppermann** [comment]
Hey @Herz3h, great thank you for the PR.

Can you please just fix it, so that the test does not fail on php 5.6

**Comment by lukasoppermann** [comment]
Awesome, if you can fix the two issues (linting issues) to make the test pass, this can be merged.

**Comment by lukasoppermann** [comment]
Sorry, still one left, you should be able to run `vendor/bin/php-cs-fixer fix -v --diff --dry-run` locally to see those issues, correct?

**Comment by Herz3h** [comment]
I've tried that command but I get an error saying class PhpCsFixer/Finder could not be found

**Comment by lukasoppermann** [comment]
ahh, you may have to install it manually as well. Sorry, I am not using composer anymore (just like php) but it was a bit of a hassle for me to set it up as well. You did run composer install, I assume?

**Comment by Herz3h** [comment]
yes, I did run composer install, will check how to install the PhpCsFixer/Finder then

**Comment by lukasoppermann** [comment]
Hey @Herz3h whenever you can rebase and fix the on linting error I will merge this one.

We also need to update the docs to reflect the new behavior.

**Comment by Herz3h** [comment]
@lukasoppermann I've still no way to run linting tests locally, so I've just tried to guess what the linting problem is. Hopefully test passes. Also updated the readme.

**Comment by lukasoppermann** [comment]
Looks great. 👍

**Pull request merged**
